# **Noise in Image Restoration**
## Muhammad Reza Fahlevi (NIM: 181401139)
----

### Definisi Image
Image the didefinisikan sebagai suatu intesitas I pixel citra pada posisi (x,y), yaitu $I(x,y)$. Secara umum, citra terbagi atas 3 kategori:

* Citra biner (monochrome)
* Citra abu-abu (grayscale)
* Citra berwarna

Citra biner memiliki intensitas pixel 0 (nilai yang paling gelap) dan 255 (nilai yang paling terang). Citra abu - abu merupakan citra yang nilai pixelnya pada posisi $(x, y)$ merupakan rata-rata dari nilai rgbnya. Sedangkan citra berwarna adalah citra yang setiap pixel pada $(x, y)$ memiliki 3 nilai, yaitu $(red, green, blue)$
$$
\begin{align}
f(x, y) &= 
\begin{bmatrix}
r(x, y) \\
g(x, y) \\
b(x, y)
\end{bmatrix}
\end{align}
$$

### Model Degradasi Image
Degradasi pada image dapat dimodelkan sebagai berikut.

Jika $h(x, y)$ adalah fungsi degradasi, $\eta(x, y)$ adalah fungsi noise. Maka, image terdegradasi $g(x, y)$ untuk inputan image $\phi(x,y)$ di definisikan sebagai
$$
g(x, y) = h(x, y) \ast \phi(x, y) + \eta(x, y)
$$

Yang mana $\ast$ merupakan operator konvulusi. Restorasi merupakan proses perbaikan suatu citra yang pada pixelnya terdapat noise. Untuk merestorasi citra, maka kita harus menurunkan (mendegradasi) citra tersebut.

### Noise pada Image
Didefinisikan sebagai:
$$
n(x, y) = f(x, y) + \eta(x, y)
$$
Yang mana $n(x, y)$ adalah citra yang terdapat noise dan $f(x, y)$ adalah citra original (atau citra yang diharapkan, tanpa noise).

Pada notebook ini, noise yang akan dibahas adalah:

* Gaussian noise
* Impulse noise (salt and pepper)
* Poisson noise
* Speckel noise

### Gaussian Noise
Gaussian noise adalah noise pada citra $f(x, y)$ yang terdistribusi normal.

**Definition $\text{[Gauss Distribution]}$.** Jika $\mu$ adalah rata-rata dan $\sigma^2$ adalah variasi, maka distribusi untuk random variable X adalah
$$
G(x; \mu, \sigma) = \frac{1}{\sqrt{2 \pi}\sigma} exp\left\{-\frac{1}{2 \sigma^2}(x - \mu)^2 \right\}
$$
atau
$$
G(x, y; \mu, \sigma) = \frac{1}{2 \pi\sigma^2} exp\left\{-\frac{1}{2 \sigma^2}(x^2 + y^2) \right\}
$$
untuk noise pada citra $f(x, y)$

### Impulse Noise
Didefinisikan sebagai
$$
\begin{align}
P(z) &= \begin{cases}
P_a && \text{if } z = a \\
P_b && \text{if } z = b
\end{cases}
\end{align}
$$

### Poisson Noise
Didefinisikan sebagai
$$
p(x; \lambda t) = \frac{e^{\lambda t}(\lambda t)^x}{x!}
$$

### Speckel Noise
Speckle noise can be generated by multiplying random pixel values with different pixels of an image.

In [2]:
#Prepare the tools
import numpy as np
import random
print("Initialize.... \nDone.")

Initialize.... 
Done.


In [3]:
Pixel = np.matrix([
    [123, 321, 123],
    [123, 532, 123],
    [98, 12, 321]
])
Noise = np.random.normal(0, 2, size= (3, 3))
Noise
print(f"Pixel: \n{Pixel}\nNoise:\n {Noise} \nPixel with noise\n {Pixel + Noise}")

Pixel: 
[[123 321 123]
 [123 532 123]
 [ 98  12 321]]
Noise:
 [[ 0.49848639 -1.30062922  1.36659205]
 [-5.53448321 -0.19500632  0.69103171]
 [-1.41848636 -0.48238745  1.69381804]] 
Pixel with noise
 [[123.49848639 319.69937078 124.36659205]
 [117.46551679 531.80499368 123.69103171]
 [ 96.58151364  11.51761255 322.69381804]]
